name: Run Specified Python File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Name of the Python file to run'
        required: true
        type: string

jobs:
  find-and-run-file:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # You can adjust the Python version as needed

    - name: Install Python dependencies dynamically
      run: |
        FILE_PATH=$(find . -name ${{ github.event.inputs.filename }} | head -n 1)
        if [ -z "$FILE_PATH" ]; then
          echo "File not found!"
          exit 1
        fi
        echo "Running $FILE_PATH..."
        # Updated regex to capture more complex imports
        DEPS=$(grep -oP '(?<=^import )\w+|(?<=^from )\w+' "$FILE_PATH" | sort -u | tr '\n' ' ')
        if [ -n "$DEPS" ]; then
          echo "Installing dependencies found in the file: $DEPS"
          pip install $DEPS
        else
          echo "No dependencies found to install."
        fi

    - name: Execute the Python file
      run: |
        python $FILE_PATH
