name: Run Specific Python File

on:
  workflow_dispatch:
    inputs:
      filename:
        description: 'Name of the Python file to run'
        required: true
        type: string

jobs:
  find-and-run-file:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Python dependencies (if any)
      run: |
        python -m pip install --upgrade pip

    - name: Find and run the specified Python file
      run: |
        FILE_PATH=$(find . -name ${{ github.event.inputs.filename }} | head -n 1)
        DEPS=$(grep -oP '^import \K\w+' "$FILE_PATH" | tr '\n' ' ')
        pip install $DEPS
        python "$FILE_PATH"

